### ISSUE TITLE
Canned Achievements

### ISSUE THREAD

**Issue by richdouglasevans** [muyjohno/desperado#51]
Hey Johno,

__What's the best way to seed the database with a set of canned achievements?__

I plan to deploy an instance of Desperado for the Oxford league.

The achievements you've listed for the Reading league look good and I'd just like to run with those. I can't be arsed adding the achievements via the UI.

I'm thinking of creating a new migration that I'd just drop into `db/migrate` so that when I run the migrations the `achievements` table is seeded. Yeah, I still have to key in the achievements but the achievements are captured in a versioned text file so I'm fine with that.

Is that the Ruby-esque way of doing it though? How would you do it? (Note: I have zero Rails experience.)

**Comment by richdouglasevans** [comment]
Ah, I've just discovered that I can extend rake with custom tasks in the `lib/tasks` directory and invoke it as a task distinct from the migrations.

Maybe that's a "better" way rather than lumping canned data into a migration?

**Comment by muyjohno** [comment]
Yes, if possible keep data out of migrations (which should only be for required structural changes). Creating a rake task for some preset achievements seems like the best approach to me. I don't have much experience in rake tasks but if you whip something up and create a PR for it I'll take a look!

**Comment by richdouglasevans** [comment]
Thanks for the steer Johno; I'll have a look at this on Sunday afternoon -- along with an Oxford Blues theme -- if the locals [bite at my suggestion](http://netrunners.co.uk/forumdirectory/phpBB3/viewtopic.php?f=23&t=989).
